# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedticket',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
